import express from "express";
import authRoutes from "./routes/auth.routes.js";
import sedesRoutes from "./routes/sedes.routes.js";
import userRoutes from "./routes/user.routes.js";
import sucuRoutes from "./routes/sucursal.routes.js";
import marcasRoutes from "./routes/marcas.routes.js";
import categoriaRoutes from "./routes/categoria.routes.js";
import equipoRoutes from "./routes/equipo.routes.js";
import perifericoRoutes from "./routes/periferico.routes.js";
import impresoraRoutes from "./routes/impresora.routes.js";
import tonerRoutes from "./routes/toner.routes.js";
import tonerImpresoraRoutes from "./routes/toner-impresora.routes.js";
import contratoRoutes from "./routes/contrato.routes.js";
import prestamoRoutes from "./routes/prestamo.routes.js";
import trasladoRoutes from "./routes/traslados.routes.js";
import bajasRoutes from "./routes/baja.routes.js";
import actaRoutes from "./routes/acta.routes.js";
import manteRoutes from "./routes/mante.routes.js";
import devolucionRoutes from "./routes/devolucion.routes.js";
import tiposRoutes from "./routes/tipos.routes.js";
import estadosRoutes from "./routes/estado.routes.js";
import proveedorRoutes from "./routes/proveedor.routes.js";
import perfilesAccesoRoutes from "./routes/perfilesAcceso.routes.js";
import permisosRoutes from "./routes/permisos.routes.js";
import checklistRoutes from "./routes/checklist.routes.js";

const routerApi = (app) => {
  const router = express.Router();
  app.use("/api", router);

  router.use("/auth", authRoutes);
  router.use("/sedes", sedesRoutes);
  router.use("/users", userRoutes);
  router.use("/sucursales", sucuRoutes);
  router.use("/marcas", marcasRoutes);
  router.use("/categorias", categoriaRoutes);
  router.use("/equipos", equipoRoutes);
  router.use("/perifericos", perifericoRoutes);
  router.use("/impresoras", impresoraRoutes);
  router.use("/toners", tonerRoutes);
  router.use("/toner-impresora", tonerImpresoraRoutes);
  router.use("/contrato", contratoRoutes);
  router.use("/prestamos", prestamoRoutes);
  router.use("/traslados", trasladoRoutes);
  router.use("/bajas", bajasRoutes);
  router.use("/actas", actaRoutes);
  router.use("/mantenimientos", manteRoutes);
  router.use("/devoluciones", devolucionRoutes);
  router.use("/tipos", tiposRoutes);
  router.use("/estados", estadosRoutes);
  router.use("/proveedores", proveedorRoutes);
  router.use("/perfiles-acceso", perfilesAccesoRoutes);
  router.use("/permisos", permisosRoutes);
  router.use("/checklist", checklistRoutes);
};

export default routerApi;
