// src/store/authSlice.ts
import { Usuario } from "@/pages/configuracion/usuarios/interfaces/usuarios";
import { createSlice, PayloadAction } from "@reduxjs/toolkit";

interface AuthState {
  user: Usuario | null;
}

// Initial state for the auth slice
const initialState: AuthState = {
  user: null,
};

// Create the auth slice with initial state and reducers
const authSlice = createSlice({
  // Name of the slice
  name: "auth",
  // Initial state of the slice
  initialState,
  // Reducers for the slice
  reducers: {
    // Login success reducer
    loginSuccess: (state, action: PayloadAction<Usuario>) => {
      state.user = action.payload;
    },
    // Logout reducer
    logout: (state) => {
      state.user = null;
    },
  },
});

// Export the actions generated by createSlice
export const { loginSuccess, logout } = authSlice.actions;
// Export the reducer to be used in the store
export default authSlice.reducer;
